services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: espace_comedie
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;'
    ports:
      - "3308:3306"
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - mysql_data:/var/lib/mysql
    
    

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=espace_comedie
      - STRIPE_SECRET_KEY=sk_test_51RdoIJPXUg296p0SlqBGFT9Ne9YaG7NCaXdUqN9TxT5R83Xjo6ycEwxnCxN6hPiE7Dx7MdAB9NjgcZzPJjHJXaiE003t1kve0j
      - FRONTEND_URL=http://localhost:5173
      - NODE_ENV=development
      - JWT_SECRET=Apres_lheure_cest_plus_lheure_franchement
      # Configuration SMTP Gmail (local et production)
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=junior97301@gmail.com
      - SMTP_PASS=azwrabuivhturkpq
      - FROM_EMAIL=lespacecomedie@gmail.com
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
      - backend_logs:/app/logs
      - backend_uploads:/app/uploads
      - ./frontend/public/assets/img/spectacles:/app/frontend_public_assets/spectacles
      - ./frontend/public/assets/img/photo_artiste:/app/frontend_public_assets/photo_artiste
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.simple
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend

volumes:
  mysql_data:
    driver: local
  backend_logs:
    driver: local
  backend_uploads:
    driver: local