FROM node:24-alpine3.20

WORKDIR /app

# Créer un utilisateur non-root
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nodejs -u 1001

COPY package*.json ./
RUN npm install 

# Copier les fichiers avec les bonnes permissions
COPY --chown=nodejs:nodejs . .

# Changer les permissions
RUN chown -R nodejs:nodejs /app

USER nodejs

EXPOSE 5000
CMD ["node", "src/server.js"]
