FROM node:24-alpine3.20

WORKDIR /app

# Installer les dépendances système nécessaires
RUN apk add --no-cache python3 make g++

# Copier package.json et package-lock.json d'abord
COPY package*.json ./

# Installer les dépendances
RUN npm install --legacy-peer-deps

# Copier le reste des fichiers
COPY . .

# Créer les dossiers nécessaires
RUN mkdir -p uploads logs

EXPOSE 5000

# Commande de démarrage
CMD ["node", "src/server.js"]
